gcc src/CharacterReader.c -o CharacterReader -lrt
gcc src/HighAlpha.c -o HighAlpha -lrt
gcc src/LowAlpha.c -o LowAlpha -lrt
gcc src/Math.c -o Math -lrt
gcc src/Starter.c -o Starter -lrt

mv CharacterReader HighAlpha LowAlpha Math Starter bin/

